version: '3'
services:
  core:
    container_name: app
    image: jsf/app
    build:
      context: ../
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "8080:8080"
      - "4848:4848"
    depends_on:
      - banco
    links:
      - "banco:host-banco"
  banco:
    container_name: banco
    image: jsf/banco
    build: ./banco
    ports:
      - "5433:5432"